// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/anthoz69/salepage-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

type AuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthUseCase) EXPECT() *AuthUseCase_Expecter {
	return &AuthUseCase_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with no fields
func (_m *AuthUseCase) GetMe() (*domain.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthUseCase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type AuthUseCase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
func (_e *AuthUseCase_Expecter) GetMe() *AuthUseCase_GetMe_Call {
	return &AuthUseCase_GetMe_Call{Call: _e.mock.On("GetMe")}
}

func (_c *AuthUseCase_GetMe_Call) Run(run func()) *AuthUseCase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthUseCase_GetMe_Call) Return(_a0 *domain.User, _a1 error) *AuthUseCase_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthUseCase_GetMe_Call) RunAndReturn(run func() (*domain.User, error)) *AuthUseCase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
