// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/anthoz69/salepage-api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

type UserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUseCase) EXPECT() *UserUseCase_Expecter {
	return &UserUseCase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: user
func (_m *UserUseCase) CreateUser(user *domain.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *UserUseCase_Expecter) CreateUser(user interface{}) *UserUseCase_CreateUser_Call {
	return &UserUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *UserUseCase_CreateUser_Call) Run(run func(user *domain.User)) *UserUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *UserUseCase_CreateUser_Call) Return(_a0 error) *UserUseCase_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserUseCase_CreateUser_Call) RunAndReturn(run func(*domain.User) error) *UserUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
