app:
  port: ":3001"

db:
  host: localhost
  user: postgres
  password: postgres
  name: salepage
  port: 5432
  tls: false

redis:
  host: localhost
  port: 6379
  password: 
  db: 0

jwt:
  secret: secret